services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network
    environment:
      - NEXT_PUBLIC_DB_HOST=postgres
      - NEXT_PUBLIC_DB_PORT=5432
      - NEXT_PUBLIC_DB_USER=postgres
      - NEXT_PUBLIC_DB_PASSWORD=postgres
      - NEXT_PUBLIC_DB_NAME=mydb

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network


volumes:
  postgres_data:

